version: "3.9"
services:
networks:
 roboshop:
  driver: bridge
 web:
  image: web:v1
  container_name: web
  depends_on:
  - catalogue 
 mongodb:
  image: mongodb:v1
  container_name: mongodb
 catalogue:
  image: catalogue:v1
  container_name: catalogue
  depends_on:
  - mongodb
